#!/usr/bin/perl -w

use strict;

package Notes::Comment;
	use strict;
	use Date::Manip::Date;
	use feature 'signatures';
	no warnings 'experimental::signatures';

	sub new($class, $update) {
		my $self=$update;
		bless($self, $class);
		return $self;
	}
	
	sub date($self) {
		return $self->{date};
	}

	sub date_serial($self) {
		my $dm=new Date::Manip::Date;
		my $err=$dm->parse($self->date());
		# We return 1.1.1970
		if ($err) {
			return 0;
		}
		my $serial=$dm->secs_since_1970_GMT();
		return $serial;
	}

	sub user($self) {
		return $self->{user};
	}

	sub text($self) {
		return $self->{text};
	}

1;

package Notes::Noteupdate;
        use strict;
        use feature 'signatures';
        no warnings 'experimental::signatures';

	sub new($class, $update) {
		my $self=$update;
		bless($self, $class);
		return $self;
	}

	sub note_id($self) {
		return $self->{properties}{id};
	}

	sub status($self) {
		return $self->{properties}{status};
	}

	sub comments($self) {
		return map { new Notes::Comment($_) } @{$self->{properties}{comments}};
	}
1;

package Notes::API;
	use strict;
	use LWP::UserAgent;
	use LWP::Authen::OAuth2;
	use URI::Encode qw/uri_encode/;
	use Data::Dumper;
	use HTTP::Request::Common;
	use File::Slurp qw/read_file write_file/;
	use List::Util qw/any/;
	use FindBin qw/$Bin/;
	use JSON;
	use feature 'signatures';
	no warnings 'experimental::signatures';

	sub new($class, $api) {
		my $self = {
			uri => $api->{uri},
			limit => $api->{limit} // 100
		};

		bless($self, $class);

		$self->oauth2_refresh_token($api);

		return $self;
	}

	sub oauth2_token_read($self) {
		my $tokens=read_file("$Bin/.oauth2_tokens", err_mode => "quiet");
		return $tokens // undef;
	}

	# Check if token authenticates against api and returns the right permissions
	sub oauth2_token_valid($self, $api) {
		my $r=$self->{oauth2}->get($api->{auth}{permissionuri});

		return 0 if (!$r->is_success());

		my $p=from_json($r->decoded_content());

		return 0 if (!defined($p->{permissions}));

		return 1 if (any { $_ =~ /write_notes/; } @{$p->{permissions}});

		return 0;
	}


	sub oauth2_refresh_token($self, $api) {

		my $tokens=$self->oauth2_token_read();

		my $oauth2 = LWP::Authen::OAuth2->new(
			client_id => $api->{auth}{clientid},
			client_secret => $api->{auth}{clientsecret},
			authorization_endpoint => $api->{auth}{authorizationuri},
			token_endpoint => $api->{auth}{tokenuri},
			redirect_uri => "https://localhost/noteisdue/authenticated",

			# Optional hook, but recommended.
			save_tokens => \&oauth2_save_tokens,
			save_tokens_args => [ $self ],
			scope => $api->{auth}{scope},

			# This is for when you have tokens from last time.
			token_string => $tokens
		);

		$self->{oauth2}=$oauth2;

		if (defined($tokens)) {
			if ($self->oauth2_token_valid($api)) {
				printf("Token authentication is valid\n");
				return;
			}
			return;
		}

		my $istty = -t STDIN && (-t STDOUT || !(-f STDOUT || -c STDOUT)) ;

		if (!$istty) {
			die("Cant refresh token noninteractively - please run in terminal");
		}

		# Interactively create token with user
		printf("Authenticate at: %s\n", $oauth2->authorization_url());
		printf("Enter url you got redirected to: ");
		my $code=<STDIN>;
		chomp($code);
		$code=~s/^.*code=//;

		$oauth2->request_tokens(code => $code);	

		if (defined($oauth2->token_string)) {
			printf("Got token: %s\n", $oauth2->token_string);
		}
	}

	# Callback - reverted self/tokens
	sub oauth2_save_tokens($tokens, $self) {
		write_file("$Bin/.oauth2_tokens", $tokens);
	}

	sub fetch($self, $left, $bottom, $right, $top) {
		my $area=($top-$bottom)*($right-$left);

		# If the area is to large split it down
		if ($area > 25) {
			my $xmid=$left+($right-$left)/2;
			my $ymid=$bottom+($top-$bottom)/2;

			my @notes;

			push @notes, @{$self->fetch($left, $ymid, $xmid, $top)};
			push @notes, @{$self->fetch($xmid, $ymid, $right, $top)};
			push @notes, @{$self->fetch($left, $bottom, $xmid, $ymid)};
			push @notes, @{$self->fetch($xmid, $bottom, $right, $ymid)};

			return \@notes;
		}

		printf("Fetching notes in bbox %f, %f, %f, %f area %f\n", $left, $bottom, $right, $top, $area);

		my $uri=sprintf("%s/notes/?bbox=%f,%f,%f,%f&format=json&limit=%d",
			$self->{uri}, $left, $bottom, $right, ${top}, $self->{limit});

		my $response=$self->{oauth2}->get($uri);

		if (!$response->is_success()) {
			return undef;
		}

		my $data=from_json($response->decoded_content);

		my @updates=map { new Notes::Noteupdate($_) } @{$data->{features}};

		printf("Fetched %d notes in bbox %f, %f, %f, %f area %f\n", scalar @updates, $left, $bottom, $right, $top, $area);

		return \@updates;
	}

	use URI::Encode;

	sub note_close($self, $noteid, $comment) {
		my $uri=sprintf("%s/notes/%d/close?text=%s",
			$self->{uri}, $noteid, uri_encode($comment));

		my $response=$self->{oauth2}->post($uri);

		if (!$response->is_success()) {
			return undef;
		}

		return $response->decoded_content();
	}

	sub note_reopen($self, $noteid) {
		my $uri=sprintf("%s/notes/%d/reopen",
			$self->{uri}, $noteid);

		my $response=$self->{oauth2}->post($uri);

		if (!$response->is_success()) {
			return undef;
		}

		return $response->decoded_content();
	}

	sub note_comment($self, $noteid, $comment) {
		my $uri=sprintf("%s/notes/%d/comment?text=%s",
			$self->{uri}, $noteid, uri_encode($comment));

		my $response=$self->{oauth2}->post($uri);

		if (!$response->is_success()) {
			return undef;
		}

		return $response->decoded_content();
	}
1;

package Notes::Database::Note;
   	use strict;
	use Data::Dumper;
        use feature 'signatures';
        no warnings 'experimental::signatures';

	sub new($class, $dbh, $row) {

		my $self={
			row=>$row,
			dbh=>$dbh
		};
		bless($self, $class);

		return $self;
	}

	sub dbid($self) {
		return $self->{row}{id};
	}

	sub noteid($self) {
		return $self->{row}{noteid};
	}

	sub action($self) {
		return $self->{row}{action};
	}

	sub username($self) {
		return $self->{row}{username};
	}

	sub done($self) {
		my $sql=$self->{dbh}->prepare("update noteactions set done = true where id = ?") || warn $DBI::errstr;
		$sql->execute($self->dbid()) || warn $DBI::errstr;
		$sql->finish();
	}

	sub lastcomment_update($self, $commenttimestamp) {
		# Update lastcomment_update to latest comment timestamp
		my $sql=$self->{dbh}->prepare("
			update	noteactions
			set	lastcommenttimestamp = to_timestamp(?)
			where	id = ?
			and	done = false
			and	lastcommenttimestamp < to_timestamp(?)") || die $DBI::errstr;
		$sql->execute($commenttimestamp, $self->dbid(), $commenttimestamp);
		$sql->finish();
	}

1;

package Notes::Database;

   	use strict;
        use LWP::UserAgent;
        use JSON;
        use feature 'signatures';
        no warnings 'experimental::signatures';

	sub new($class, $dbconfig) {
		my $self=$dbconfig;
		bless($self, $class);

		$self->connect();

		return $self;
	}

	sub connect($self) {

		my $dbh = DBI->connect($self->{host}, $self->{username}, $self->{password}) or die $DBI::errstr;
		$dbh->{pg_enable_utf8} = 1;

		$self->{dbh}=$dbh;
	}

	sub noteexists($self, $noteid, $commenttimestamp) {
		my $sql=$self->{dbh}->prepare("select id from noteactions where noteid = ? and commenttimestamp = to_timestamp(?)") || die $DBI::errstr;
		$sql->execute($noteid, $commenttimestamp);
		my $row=$sql->fetchrow();
		$sql->finish();

		return defined($row);
	}
	sub addnoteaction($self, $noteid, $commenttimestamp, $action, $actiontimestamp, $user) {
		if (noteexists($self, $noteid, $commenttimestamp)) {
			printf("%20s Already in database\n", $noteid);
			return 0;	
		}

		my $sql=$self->{dbh}->prepare("
			insert into noteactions (
				noteid,
				due,
				commenttimestamp,
				lastcommenttimestamp,
				action,
				username)
			values ( ?, to_timestamp(?), to_timestamp(?), to_timestamp(?), ?, ?)") || die $DBI::errstr;

		my $err=$sql->execute(
			$noteid,
			$actiontimestamp,
			$commenttimestamp,
			$commenttimestamp,
			$action,
			$user);
		$sql->finish();

		return $err // 0;
	}

	sub note_fetch_noteid($self, $noteid) {
		my $sql=$self->{dbh}->prepare("
			select	*
			from	noteactions
			where	noteid = ?") || die $DBI::errstr;
		my $err=$sql->execute($noteid);

		my @notes;
		while(my $row=$sql->fetchrow_hashref()) {
			push @notes, new Notes::Database::Note($self->{dbh}, $row);
		}
		$sql->finish();

		return \@notes;
	}

	sub duenotes($self) {
		my $sql=$self->{dbh}->prepare("
			select	*
			from	noteactions
			where	done = false
			and	due < 'now'::timestamp") || die $DBI::errstr;
		my $err=$sql->execute();

		my @notes;
		while(my $row=$sql->fetchrow_hashref()) {
			push @notes, new Notes::Database::Note($self->{dbh}, $row);
		}

		$sql->finish();

		return \@notes;
	}


1;

use strict;
use feature 'signatures';
use Data::Dumper;
use Getopt::Long::Descriptive;
use File::Slurp;
use List::Util;
use Date::Manip qw/ParseDate/;
use FindBin qw/$Bin/;
use DBI;
use POSIX qw/strftime/;

# We want to track comments on notes we are waiting for
sub note_process_noncommand($config, $a, $d, $update, $comment) {
	my $notes=$d->note_fetch_noteid($update->note_id());

	# We dont have any commands for this note
	if (scalar @$notes == 0) {
		return;
	}

	for my $note ( @$notes ) {
		$note->lastcomment_update($comment->date_serial());
	}
}

sub note_process($config, $a, $d, $update, $comment) {
	my $text=$comment->text();
	if (!defined($text)) {
		printf("comment->text() is not defined\n");
		print Dumper($comment);
		print Dumper($update);
		return;
	}

	my @lines=split(/\n/, $text);

	# No comments - nothing to process
	return if (scalar @lines == 0);

	# Only process first line comments with these commands
	if ($lines[0] !~ /(reopen|notify|autoclose):\s*(.+)$/) {
		note_process_noncommand($config, $a, $d, $update, $comment);
		return;
	}

	my $action=$1;
	my $datestring=$2;

	my $dm=new Date::Manip::Date;
	my $err=$dm->parse($datestring);
	if ($err) {
		printf("Could not parse note %s first line datestring: %s returned: %s\n", $update->note_id(), $datestring, $err);
		return;
	}
	my $datespec=$dm->secs_since_1970_GMT();

	if ($action =~ /reopen/) {
		printf("%20s found reopen %s %s\n", $update->note_id(), $datestring, $comment->date());
		if ($d->addnoteaction($update->note_id(), $comment->date_serial(), "reopen", $datespec, $comment->user())) {
			$a->note_close($update->id(), "Will be reopened per request of User %s", $comment->user());
		}
	} elsif ($action =~ /notify/) {
		printf("%20s found notify %s %s\n", $update->note_id(), $datestring, $comment->date());
		$d->addnoteaction($update->note_id(), $comment->date_serial(), "notify", $datespec, $comment->user());
	} elsif ($action =~ /autoclose/) {
		printf("%20s found autoclose %s %s\n", $update->note_id(), $datestring, $comment->date());
		if ($d->addnoteaction($update->note_id(), $comment->date_serial(), "autoclose", $datespec, $comment->user())) {
			$a->note_comment($update->note_id(), sprintf("Got autoclose for note per request of User %s", $comment->user()));
		}
	}

	return;
}

sub updatefromapi($config, $a, $d) {
	my $updates=$a->fetch(
		$config->{bbox}{left},
		$config->{bbox}{bottom},
		$config->{bbox}{right},
		$config->{bbox}{top});

	if (!defined($updates)) {
		die("API Failed");
	}

	printf("Processing notes from API\n");

	foreach my $update ( @{$updates} ) {
		foreach my $comment ( $update->comments() ) {

			my $user=$comment->user();
			next if (!defined($user) || $user eq '');

			# Allowed user list?
			if (defined($config->{users})) {
				if (!scalar grep { $user eq $_ } @{$config->{users}}) {
					next;
				}
			}

			note_process($config, $a, $d, $update, $comment);
		}
	}
}

sub actionifdue($config, $a, $d) {
	my $dbnotes=$d->duenotes();

	printf("Processing due notes from database\n");

	foreach my $dbnote ( @{$dbnotes} ) {
		if ($dbnote->action() eq 'reopen') {
			printf("%20s Reopening\n", $dbnote->noteid());
			$a->note_reopen($dbnote->noteid());
			$dbnote->done();
		} elsif ($dbnote->action() eq 'notify') {
			printf("%20s Notify\n", $dbnote->noteid());
			$a->note_comment($dbnote->noteid(), sprintf("User %s requested a notification", $dbnote->username()));
			$dbnote->done();
		} elsif ($dbnote->action() eq 'autoclose') {
			printf("%20s Autoclosing\n", $dbnote->noteid());
			$a->note_close($dbnote->noteid(), sprintf("User %s requested autoclose - closeing", $dbnote->username()));
			$dbnote->done();
		}
	}
}

my ($opt, $usage) = describe_options(
	'$Bin %o <some-arg>',
	[ 'configfile=s',	"Config filename", { default => "noteisdueconfig.json" } ],
	[],
	[ 'help',               "print usage message and exit", { shortcircuit => 1 } ],
);

my $config=from_json(read_file($opt->configfile));

my $a=new Notes::API($config->{api});
my $d=new Notes::Database($config->{dbconfig});

updatefromapi($config, $a, $d);
actionifdue($config, $a, $d);

if (defined($config->{touchfile})) {
	write_file($config->{touchfile}, strftime("%Y-%m-%dT%H:%M:%S", localtime(time())));	
}
